# Generated by Django 2.2.8 on 2019-12-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('male', 'male'), ('female', 'female')], max_length=10),
        ),
    ]
