# Generated by Django 2.2.8 on 2020-01-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200102_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('krw', 'KRW'), ('usd', 'USD')], max_length=3),
        ),
    ]
