# Generated by Django 2.2.8 on 2020-01-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200102_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='nema',
            new_name='name',
        ),
    ]
