# Generated by Django 2.2.9 on 2020-01-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200118_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bads',
            new_name='beds',
        ),
    ]
