# Generated by Django 2.2.9 on 2020-01-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20200127_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Comfirmed'), ('canceled', 'Canceled')], default='pending', max_length=12),
        ),
    ]
