# Generated by Django 2.2.9 on 2020-02-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20200203_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Comfirmed'), ('pending', 'Pending')], default='pending', max_length=12),
        ),
    ]
