# Generated by Django 2.2.9 on 2020-02-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20200210_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Comfirmed'), ('canceled', 'Canceled')], default='pending', max_length=12),
        ),
    ]
