# Generated by Django 2.2.9 on 2020-02-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_auto_20200211_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Comfirmed'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=12),
        ),
    ]
