# Generated by Django 2.2.9 on 2020-02-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_auto_20200218_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'Pending'), ('confirmed', 'Comfirmed')], default='pending', max_length=12),
        ),
    ]
