# Generated by Django 2.2.14 on 2020-08-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_auto_20200809_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'Pending'), ('confirmed', 'Comfirmed')], default='pending', max_length=12),
        ),
    ]
